version: "3"
services:

  php:
    volumes:
      - './src/:/var/www/html'
      - './.docker/php/supervisor.conf:/etc/supervisord.conf'
    tty: true
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    links:
      - "db:database"
      - "redis:redis"
    networks:
      internal:
      traefik:

  nginx:
    image: nginx:alpine
    volumes:
      - './src:/var/www/html'
      - './.docker/nginx/nginx/conf.d/:/etc/nginx/conf.d/'
      - './.docker/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf'
    labels:
      traefik.backend: domain.test
      traefik.frontend.rule: "Host:library.test"
      traefik.docker.network: traefik
      traefik.port: 80
    networks:
      internal:
      traefik:
    depends_on:
      - php
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_USER: 'amin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      DEFAULT_AUTHENTICATION_PLUGIN: 'mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql:rw
      - './database:/var/data'
    networks:
      - internal
    ports:
      - "3306:3306"

  # Cache server
  redis:
    image: redis:4-alpine
    volumes:
      - redis:/data:rw
    networks:
      internal:

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"

networks:
  traefik:
    external: true
  internal:
    external: false
